databases:
  - name: postgres
    databaseName: mysite
    user: mysite
    plan: free
    ipAllowList: []
services:
  - type: web
    name: rails
    plan: free
    env: ruby
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s" #puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
  name: redis
  ipAllowList: []
  plan: free
  maxmemoryPolicy: noeviction
